### ISSUE TITLE
Absolute paths are always listed, even if the note exists

### ISSUE THREAD

**Issue by auratheenby** [ulisesantana/obsidian-pending-notes#12] opened 2023-08-31 22:41 UTC
I use absolute paths in all my links, because it makes it easier for me to tell which note it is (I sometimes have duplicates in different folders), and remind me at a glance what that note might pertain to, as well as triggering an appropriate template when created. The issue is that it makes this plugin completely unusable for me, because it lists **_all_** the links in my vault, rather than just the ones that don't yet go anywhere.

It was a bit confusing at first, made me think I had misspelled hundreds of links even with autocomplete. But after I looked at the links themselves, I discovered that no, the links are fine - the plugin just doesn't recognize that.

**Comment by ulisesantana** [comment] 2023-09-03 07:58
I'm not sure why that is happening. Could you give me an example so I can reproduce it? I don't know how to put an absolute path in a wikilink

**Comment by auratheenby** [comment] 2023-09-03 17:30
you just put a path before the note name, like [[folder/folder/note|alias]]

**Comment by mariomui** [comment] 2023-10-04 03:45
<img width="1680" alt="Screen Shot 2023-10-03 at 8 32 24 PM" src="https://github.com/ulisesantana/obsidian-pending-notes/assets/29618692/021ef994-36d2-4aea-8bb4-7d9ca9d5c36d">
I swore i uploaded a screen shot for you before, oh well, here it is.

Focus on B_churn_box, you can see 53 mentions of the shadow note(sorry, pending note) but that is not the case.

It could also be seen as a feature since most note takers mistakenly add the directory structure the linking via some auto link updating software.

**Comment by Bertie2011** [comment] 2023-10-06 19:21
Aw man, this seems like the only plugin that counts the amount of links to missing notes and it doesn't work for my use case.

I'd love it if this could be fixed for absolute links 😅

**Comment by mariomui** [comment] 2023-10-16 09:17
@Bertie2011  There is a usecase with note composer where you force the note to merge with a note that is on the root level
you take `Box/mynote.md` and do a note composer merge to mynote.md in the root level. This will automatically fix all the notes to remove the folder prefix. Then you move the note back into the folder.

**Comment by Bertie2011** [comment] 2023-10-16 13:12
I don't want to modify existing notes, I wish the plugin panel wouldn't show absolute links that reference real files

**Comment by ulisesantana** [comment] 2023-10-19 11:20
Version 0.8.0 should fix this issue. Please check if it is working for you. I'm worried about Windows because doesn't use the same character for file path as Linux and MacOS. I don't know if Obsidian handle this under the hood or I need to bear it in mind.

**Comment by Bertie2011** [comment] 2023-10-19 13:05
It almost works (verified on windows)! Idk if it's an unrelated issue, but links to notes containing `'` always seem to appear in the panel. Could that be an escaping issue?

**Comment by ulisesantana** [comment] 2023-10-19 22:06
The apostrophe issue should fixed on 0.8.1. It was an issue related only with wikilinks using paths. Thank you for raising up the bugs. I hope this issue ends here 😅.

**Comment by Bertie2011** [comment] 2023-10-20 04:56
Yeah I no longer see any notes on my side that aren't supposed to be there. Great job on the follow ups, glad to see it fixed! 🙏🏻

**Closed** 2023-11-08 16:50 UTC

**Comment by whoszatarash** [comment] 2025-09-25 17:28
Greetings.

I'm not entirely sure if this relates, but I think I'm facing this issue. Here's some proof:

![Image](https://github.com/user-attachments/assets/a88b7945-d8c7-4701-9ae3-96ec33e29ab9)

![Image](https://github.com/user-attachments/assets/e93b77b9-24a8-4a8f-a015-37798d230c2c)

A solid 90% of my notes have tables with links inside them. Every time I have to make use of aliases, and doing so inside tables means you must escape the vertical bar.

![Image](https://github.com/user-attachments/assets/9a4a3e4c-820f-4a3e-936f-10c11d9c275b)

@ulisesantana please take a look into this! The plugin seems wonderful and feels like I've finally found a tool for my uncreated stuff, but this single issue is deceiveing.

This is happening on Android, both plugin and Obsidian on their latests / most recent versions to date.

Hope to hear back from you soon :)
*Best regards, **Z**.*
